const actionTypes = {
    CUSTOMER_API_START: "CUSTOMER_API_START",
    CUSTOMER_API_SUCCESS: "CUSTOMER_API_SUCCESS",
    CUSTOMER_API_FAILED: "CUSTOMER_API_FAILED",

}

export default actionTypes;